version: "3"

services:
  app:
    depends_on:
      - db
    environment:
      PRETTY_URLS: "1"
      LANG: "en-GB"
      BASE_URL: "http://127.0.0.1"
      DB_TYPE: "mysql"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_USER: "webtrees"
      DB_PASS: "badpassword"
      DB_NAME: "webtrees"
      DB_PREFIX: "wt_"
      WT_USER_FILE: ./env/user
      WT_NAME_FILE: ./env/name
      WT_PASS_FILE: ./env/password
      WT_EMAIL_FILE: ./env/email
    image: ghcr.io/nathanvaughn/webtrees:latest
    #build: .
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./app/data:/var/www/webtrees/data
      - ./app/media:/var/www/webtrees/media
      - ./modules/modules_v4:/var/www/webtrees/modules_v4

  db:
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_DATABASE: "webtrees"
      MYSQL_USER: "webtrees"
      MYSQL_ROOT_PASSWORD: "badpassword"
      MYSQL_PASSWORD: "badpassword"
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 33306:3306

volumes:
  db_data:
    driver: local
  
